language: php

dist: trusty

sudo: false

git:
    depth: 1

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
    include:
        - php: hhvm
        - php: 5.5
        - php: 5.6
          env: deps=high
        - php: 7.0
          env: deps=low
    fast_finish: true

install:
  - make tests
