paths:
  - ./../../hawesko/hawesko/src
views:
  -
    name: Basic View
    layers:
      -
        name: controllers
        color: '#ccc'
        collectors:
          -
            type: className
            args:
              regex: .*controller.*
      -
        name: services
        color: '#ccc'
        collectors:
          -
            type: className
            args:
              regex: .*service.*
    ruleset:
      layerA:
        - LayerB
      layerB:
        - LayerC
        - LayerD
