paths:
  - ./../../hawesko/hawesko/src
views:
  -
    name: Basic View
    layers:
      -
        color: '#ccc'
        collectors:
          -
            type: debug
            args:
              namespace: Vinostore
    ruleset:
      layerA:
        - LayerB
      layerB:
        - LayerC
        - LayerD
