paths:
  - ./../../foo/vendor/symfony/
exclude_files:
  - .*test.*
layers:
  - name: Asset
    collectors:
      - type: bool
        must:
          - type: className
            regex: .*Asset.*
        must_not:
          - type: className
            regex: .*Assetic.*
  - name: BrowserKit
    collectors:
      - type: className
        regex: .*Component\\BrowserKit.*
ruleset:
  MainBundle:
    - Domain
  CockpitBundle:
    - Domain
